name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      NODE_ENV: 'test'
      API_VERSION: 'v1'
      DB_NAME: 'mydb'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/mydb?schema=test'
      SECRET_COOKIE_PASSWORD: ${{ secrets.DEV_SECRET_COOKIE_PASSWORD }}
      TOKEN_SECRET: ${{ secrets.DEV_TOKEN_SECRET }}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies 📦
        run: npm install

      - name: Run Linter 🛠
        run: npm run lint

      - name: Run Test 🧪
        run: npm run test

  deploy_staging:
    needs: build
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: 'Create env file'
        run: |
          touch .env.local
          echo NEXT_PUBLIC_INTERCOM_ID=${{ secrets.NEXT_PUBLIC_INTERCOM_ID}} >> .env.local
          echo NEXT_PUBLIC_HOTJAR_ID=${{ secrets.NEXT_PUBLIC_DEV_HOTJAR_ID}} >> .env.local
          echo NEXT_PUBLIC_HOTJAR_SV=${{ secrets.NEXT_PUBLIC_DEV_HOTJAR_SV}} >> .env.local
          echo SUNLIGHT_URL=https://qa-beta.sunlight.is/ >> .env.local
          echo SUNRISE_URL=https://sunrise-beta-dev.sunlight.is/ >> .env.local          
          cat .env.local

      - name: Deploy 📦
        run: cd .infra && ./deploy.sh
        env:
          APP_ENVS: |
            [
              {
                "name": "container_port",
                "value": "$container_port"
              },
              {
                "name": "DATABASE_URL",
                "value": "$DATABASE_URL"
              },
              {
                "name": "AWS_ACCESSKEY",
                "value": "$AWS_ACCESS_KEY_ID"
              },
              {
                "name": "AWS_SECRETKEY",
                "value": "$AWS_SECRET_ACCESS_KEY"
              },
              {
                "name": "BUCKET_NAME",
                "value": "$BUCKET_NAME"
              },
              {
                "name": "TOKEN_SECRET",
                "value": "$TOKEN_SECRET"
              },
              {
                "name": "SECRET_COOKIE_PASSWORD",
                "value": "$SECRET_COOKIE_PASSWORD"
              },
              {
                "name":"NEXT_PUBLIC_INTERCOM_ID",
                "value": "$NEXT_PUBLIC_INTERCOM_ID"
              },
              {
                "name":"SUNLIGHT_URL",
                "value": "$SUNLIGHT_URL"
              },
              {
                "name":"SUNRISE_URL",
                "value": "$SUNRISE_URL"
              }
            ]
          container_port: 3000
          DATABASE_URL: ${{secrets.DEV_DB_CONNECTION}}
          APP_TASK: ${{ secrets.DEV_APP_TASK_NAME }}
          APP_ECR_AUTH: ${{ secrets.DEV_ECR_REPO_AUTH }}
          APP_ECR: ${{ secrets.DEV_ECR_REPOSITORY_URL }}
          CODE_DEPLOY_S3: ${{ secrets.DEV_CODEDEPLOY_S3_NAME }}
          CODEDEPLOY_APP_NAME: ${{ secrets.DEV_CODEDEPLOY_NAME }}
          CODEDEPLOY_GROUP_NAME: ${{ secrets.DEV_CODEDEPLOY_GROUP_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_SECRET_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.DEV_APP_REGION }}
          SECRET_COOKIE_PASSWORD: ${{ secrets.DEV_SECRET_COOKIE_PASSWORD }}
          TOKEN_SECRET: ${{ secrets.DEV_TOKEN_SECRET }}
          BUCKET_NAME: sunrise-dev-environment
          NEXT_PUBLIC_INTERCOM_ID: ${{secrets.NEXT_PUBLIC_INTERCOM_ID}}
          NEXT_PUBLIC_HOTJAR_ID: ${{secrets.NEXT_PUBLIC_DEV_HOTJAR_ID}}
          NEXT_PUBLIC_HOTJAR_SV: ${{secrets.NEXT_PUBLIC_DEV_HOTJAR_SV}}
          SUNLIGHT_URL: "https://qa-beta.sunlight.is/"
          SUNRISE_URL: "https://sunrise-beta-dev.sunlight.is/"
          host: api.sunlight.is

  deploy_prod:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: 'Create env file'
        run: |
          touch .env.local
          echo NEXT_PUBLIC_INTERCOM_ID=${{ secrets.NEXT_PUBLIC_PROD_INTERCOM_ID}} >> .env.local
          echo SUNLIGHT_URL=https://grow.sunlight.is/ >> .env.local
          echo SUNRISE_URL=https://sunrise.sunlight.is/ >> .env.local   
          echo NEXT_PUBLIC_HOTJAR_ID=${{ secrets.NEXT_PUBLIC_PROD_HOTJAR_ID}} >> .env.local
          echo NEXT_PUBLIC_HOTJAR_SV=${{ secrets.NEXT_PUBLIC_PROD_HOTJAR_SV}} >> .env.local
          cat .env.local

      - name: Deploy 📦
        run: cd .infra && ./deploy.sh
        env:
          APP_ENVS: |
            [
              {
                "name": "container_port",
                "value": "$container_port"
              },
              {
                "name": "DATABASE_URL",
                "value": "$DATABASE_URL"
              },
              {
                "name": "AWS_ACCESSKEY",
                "value": "$AWS_ACCESS_KEY_ID"
              },
              {
                "name": "AWS_SECRETKEY",
                "value": "$AWS_SECRET_ACCESS_KEY"
              },
              {
                "name": "BUCKET_NAME",
                "value": "$BUCKET_NAME"
              },
              {
                "name": "TOKEN_SECRET",
                "value": "$TOKEN_SECRET"
              },
              {
                "name": "SECRET_COOKIE_PASSWORD",
                "value": "$SECRET_COOKIE_PASSWORD"
              },
              {
                "name":"NEXT_PUBLIC_INTERCOM_ID",
                "value": "$NEXT_PUBLIC_INTERCOM_ID"
              },
              {
                "name":"SUNLIGHT_URL",
                "value": "$SUNLIGHT_URL"
              },
              {
                "name":"SUNRISE_URL",
                "value": "$SUNRISE_URL"
              }
            ]
          container_port: 3000
          DATABASE_URL: ${{secrets.PROD_DB_CONNECTION}}
          APP_TASK: ${{ secrets.PROD_APP_TASK_NAME }}
          APP_ECR_AUTH: ${{ secrets.PROD_ECR_REPO_AUTH }}
          APP_ECR: ${{ secrets.PROD_ECR_REPOSITORY_URL }}
          CODE_DEPLOY_S3: ${{ secrets.PROD_CODEDEPLOY_S3_NAME }}
          CODEDEPLOY_APP_NAME: ${{ secrets.PROD_CODEDEPLOY_NAME }}
          CODEDEPLOY_GROUP_NAME: ${{ secrets.PROD_CODEDEPLOY_GROUP_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_SECRET_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.PROD_APP_REGION }}
          SECRET_COOKIE_PASSWORD: ${{ secrets.PROD_SECRET_COOKIE_PASSWORD }}
          TOKEN_SECRET: ${{ secrets.PROD_TOKEN_SECRET }}
          BUCKET_NAME: sunrise-prod-environment
          NEXT_PUBLIC_INTERCOM_ID: ${{secrets.NEXT_PUBLIC_PROD_INTERCOM_ID}}
          SUNLIGHT_URL: "https://www.sunlight.is/"
          SUNRISE_URL: "https://sunrise.sunlight.is/"
          NEXT_PUBLIC_HOTJAR_ID: ${{secrets.NEXT_PUBLIC_PROD_HOTJAR_ID}}
          NEXT_PUBLIC_HOTJAR_SV: ${{secrets.NEXT_PUBLIC_PROD_HOTJAR_SV}}
          host: api.sunlight.is